app:
  port: 5000

db: 
  driver: "mysql"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "084897"
  database: TCCT
  sslmode: disable
  timezone: Asia/Bangkok
  tablename: sustain

passwordStrength:
  checkPasswordStrength: true
  hasUppercase: true
  hasLowercase: true
  hasNumber: true
  hasSpecialCharacter: true
  length: true